name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deploy only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # You can specify the version of Node.js your app requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite app
      - name: Build the app
        run: npm run build # This runs `vite build` by default, which generates the dist folder

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          publish_dir: ./dist # The directory to deploy (the build output)
          cname: "your-custom-domain.com" # Optional, if using a custom domain
